#! /bin/bash
#  clean junk files and free up your memory cache on (Ubuntu/Debian) machine
#  F1 by Mbah Gugel

if [ "$(id -u)" != "0" ]; then
   echo " you must be a groot!" 1>&2
   exit 1
fi

clear
echo -e '
====================================[brsh]=======
# this is your mem cache before cleaning : '
awk '/MemTotal/,/SwapCached/' /proc/meminfo
echo ''

if [ "$?" != "0" ]
then
  echo "Error! Filesystem Not Found"
  exit 1
fi

echo '>>> start clearing, wait a moment please...'

echo -ne '!!!!!!!!!!!!.....( 20% clearing swap space )\r'
swapoff -a && swapon -a && sleep 1

echo -ne '!!!!!!!!!!!!!!!!!!!!......( 40% clearing buffer and pagecache )\r'
echo 1 > /proc/sys/vm/drop_caches && echo 2 > /proc/sys/vm/drop_caches &&  echo 3 > /proc/sys/vm/drop_caches && sleep 1

echo -ne '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!......( 50% clearing filesystem buffer )\r'
sync && sleep 1
	
echo -ne '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!.....( 70% cleaning trash )\r'
rm -rf /home/*/.local/share/Trash/*/* >/dev/null 2>&1
rm -rf /root/.local/share/Trash/*/*   >/dev/null 2>&1
sleep 1

echo -ne '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!( 100% finished )\r'
echo -ne '\n'

echo '# your last mem cache is : ' && echo ''
awk '/MemTotal/,/SwapCached/' /proc/meminfo
sleep 4 && clear && echo -e '
=======[ TASK COMPLETED ]======='
